export const ValidationText = {
    Title: "제목을 입력해주세요",
    Content: "내용을 입력해주세요",
    UserName: "이용자명 입력해주세요",
    Password: "비밀번호 입력해주세요",
    NewPassword: "새 비밀번호를 입력해주세요",
    ConfirmPassword: "비밀번호를 확인해주세요",
    Character: "문자를 입력해주세요",
    Images: "사진을 선택해주세요",
    Question: "문의 내용을 입력해주세요",
    Answer: "답변을 입력해주세요",
    Name: "대표자 이름을 입력하세요.",
    Phone: "대표자 연락처를 입력하세요.",
    Email: "대표자 이메일을 입력하세요.",
    Notice: "공지사항을 입력해주세요",
}
