export const NoticeType = {
    REQUESTED_QUOTE: 'REQUESTED_QUOTE',
    DELIVERED_QUOTE: 'DELIVERED_QUOTE',
    APPLIED_RESERVATION: 'APPLIED_RESERVATION',
    CANCELED_RESERVATION: 'CANCELED_RESERVATION',
    CONFIRMED_RESERVATION: 'CONFIRMED_RESERVATION',
    REVIEW: 'REVIEW',
    POINT: 'POINT',
    CHAT_MESSAGE: 'CHAT_MESSAGE',
}