export const PartMapContructionConstants ={
    AllExterior: "wholeExterior",
    Bonnet: "bonnet",
    FrontBumper: "frontBumper",
    FrontFenderLeft: "frontFenderDriver",
    FrontFenderRight: "frontFenderPassenger",
    FrontDoorLeft: "frontDoorDriver",
    FrontDoorRight: "frontDoorPassenger",
    BackDoorLeft: "backDoorDriver",
    BackDoorRight: "backDoorPassenger",
    RearFenderLeft: "rearFenderDriver",
    RearFenderRight: "rearFenderPassenger",
    SideSealLeft: "sideSillDriver",
    SideSealRight: "sideSillPassenger",
    Loop: "cLoop",
    RearBumper: "rearBumper",
    Trunk: "truck",
    DoorHandle: "doorHandle",
    SideMirror: "sideMirror",
    LifeProtectionPackage: "ppf",
    FrontPackage: "frontPackage",
    DoorEdge: "doorEdge",
    HeadLamp: "headLamp",
    TailLamp: "tailLamp",

    Wheels: "Wheels",
    DriverSeat: "DriverSeat",
    DriverSeatRight: "DriverSeatRight",
    PassengerSeatLeft: "PassengerSeatLeft",
    PassengerSeatRight: "PassengerSeatRight",

    WindshieldSideAndBack: "sideBack",
    WindshieldAll: "whole",
    WindshieldFront: "frontWindshield",
    WindshieldFirstRow: "row1",
    WindshieldSecondRow: "row2",
    WindshieldThirdRow: "row3",
    WindshieldBack: "rearWindshield",
    Sunroof: "sunRoof",

    FirstRowDriverSeat: "FirstRowDriverSeat",
    SecondRowPassengerSeatLeft: "SecondRowPassengerSeatLeft",
    ThirdRowPassengerSeatLeft: "ThirdRowPassengerSeatLeft",
    FirstRowDriverSeatRight: "FirstRowDriverSeatRight",
    SecondRowPassengerSeatRight: "SecondRowPassengerSeatRight",
    ThirdRowPassengerSeatRight: "ThirdRowPassengerSeatRight",

    BlackBoxOneChannel: "channel1",
    BlackBoxTwoChannel: "channel2",
    BlackBoxFourChannel: "channel4",
    WrappingRemoval: "rappingRemoval",
    Windshield: "windshield",
    PPFRemoval: "ppfRemoval",
    TintingRemoval: "tintingRemoval",
    Tinting: "tinting",
    BlackBox: "blackBox",
    PPFLifeProtectionPackage: "ppf",
    GlassCoating: "grassFilmCoating",
    Polish: "polish",
    LowerSoundProof: "lowerSoundproofing",
    ExternalSoundProof: "outsideSoundproofing"
}
