#### spring config ####
spring:
# datasource config
  datasource:
    url: jdbc:mariadb://localhost:3306/carcloth_backend
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
# jpa config
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate.format_sql: true
    show-sql: true
# servlet config
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
# quartz config
  quartz:
    overwrite-existing-jobs: true
    scheduler-name: CompanyUsageGuideScheduler
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
#### app config #####
# JWT info
jwt:
  secret: NzxCjvoG0GcqoNksTqc5RfUmK8fyADsoWwYxhizSx01fxEmBJiGRSHQdPUFEfbw
# Duration of access token, measured in seconds.
  accessToken:
    duration: 604800 # 604800 seconds = 7 days
  refreshToken:
    duration: 2592000 # 2592000 seconds = 30 days
# config bean storage
mintpot:
  storage: com.mintpot.carcloth.utils.LocalStorageServiceImpl
# firebase config
firebase:
  dbUrl: https://car-cloth-default-rtdb.asia-southeast1.firebasedatabase.app
  admin-config: firebase-admin-dev.json

#### logging config #####
logging:
  level:
    org.springframework.scheduling.quartz: DEBUG

appstore:
  baseurl: https://sandbox.itunes.apple.com


# SolApi configs

solapi:
  caller-id: "01029565931"
  api-key: NCS7XMCTRK3FFKHV
  api-secret: VC8LFBZ3EHFRYDX2NWMLWLHC442HZMCM



