cache:
  paths:
    - ~/.m2/repository

variables:
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean package

deploy:
  stage: deploy
  script:
    - cp target/da-backend-0.0.1-SNAPSHOT.jar /opt/da/da-backend.jar
    - sudo systemctl restart da.service